project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.md"
    - "!research/presentations/sandbox/"

website:
  title: "Emmanuel Pilliat"
  navbar:
    background: dark
    left:
      - text: "Research"
        href: research.qmd
      - text: "Teaching"
        href: teaching/teaching.qmd
      - text: "Software"
        href: coding/coding.qmd
      - text: "CV"
        href: cv.qmd
    right:
      - icon: github
        href: https://github.com/epilliat
      - icon: linkedin
        href: https://fr.linkedin.com/in/emmanuel-pilliat-18ab2b180
      - icon: envelope
        href: mailto:emmanuel.pilliat@ensai.fr

format:
  html:
    theme:
      - darkly
      - theme-aurora.scss
    css: styles.css
    toc: true
