---
title: "Teaching"
sidebar: "teaching"
---

I currently am a teaching three topics in statistics at ENSAI Rennes: Hypothesis Testing, Linear and Generalized Linear Model and Times Series (TD 2024). 


# Introduction to Hypothesis Testing

See the [Glossary](teaching/glossary.qmd) for English/French translations.
See also the note recalling some notion on [Density and Likelihood](teaching/probability/density_likelihood.qmd).


::: {.panel-tabset}

## Slides
- [Testing Models](teaching/hypothesis_testing/slides/testing_models.qmd)
- [Classical Tests on Gaussian Populations](teaching/hypothesis_testing/slides/gaussian_populations.qmd)
- [Goodness of Fit and Homogeneity Tests](teaching/hypothesis_testing/slides/goodness_of_fit_chi2.qmd)
- [Tests for Dependency](teaching/hypothesis_testing/slides/dependency.qmd)


## Lectures
- [Testing Models](teaching/hypothesis_testing/lectures/testing_models.qmd)  
- [Classical Tests on Gaussian Populations](teaching/hypothesis_testing/lectures/gaussian_populations.qmd)
- [Goodness of Fit and Homogeneity Tests](teaching/hypothesis_testing/lectures/goodness_of_fit_chi2.qmd)
- [Tests for Dependency](teaching/hypothesis_testing/lectures/dependency.qmd)



## Exercises
- [TD1](teaching/hypothesis_testing/TDs/TD1.qmd)
- [TD2](teaching/hypothesis_testing/TDs/TD2.qmd)
- [TD3](teaching/hypothesis_testing/TDs/TD3.qmd)
- [TD4](teaching/hypothesis_testing/TDs/TD4.qmd)
- [TP](teaching/hypothesis_testing/TDs/TP.qmd)

## Annals

- [Exam 2025](teaching/hypothesis_testing/annals/test_2025.qmd)
- [Correction 2025](teaching/hypothesis_testing/annals/correction_2025.qmd)

## Pluto Notebooks
- [Proba Basics](teaching/hypothesis_testing/pluto/proba_basics.html)
- [Approximation of Distributions](teaching/hypothesis_testing/pluto/distribution_comparisons.html)
- [Illustration of pvalue](teaching/hypothesis_testing/pluto/illustration_pvalue.html)

:::

# Linear and Generalized Linear Model

::: {.panel-tabset}

## Slides


### Linear Model

- [Introduction](teaching/linear_model/slides/introduction.qmd)
- [Definition of the Linear Model](teaching/linear_model/slides/linear_model.qmd)
- [Inference](teaching/linear_model/slides/inference.qmd)
- [Validation](teaching/linear_model/slides/validation.qmd)
- [Model Selection](teaching/linear_model/slides/selection.qmd)
- [ANOVA/ANCOVA](teaching/linear_model/slides/anova_ancova.qmd)

### Generalized Linear Model

:::
