<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.22">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>TD5 : Exercices complémentaires – Emmanuel Pilliat</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-7b4406b7675125bc2ba204020e191172.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-338eaa8bf8d7f1eb506da55f2b711d05.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Emmanuel Pilliat</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../teaching/teaching.html"> 
<span class="menu-text">Teaching</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../coding/coding.html"> 
<span class="menu-text">Coding</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/epilliat"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://fr.linkedin.com/in/emmanuel-pilliat-18ab2b180"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#exercice-1-loi-binomiale-négative-contrôle-qualité" id="toc-exercice-1-loi-binomiale-négative-contrôle-qualité" class="nav-link active" data-scroll-target="#exercice-1-loi-binomiale-négative-contrôle-qualité">Exercice 1 : Loi binomiale négative — Contrôle qualité</a></li>
  <li><a href="#exercice-2-analyse-statistique-de-rendements-de-cryptomonnaie" id="toc-exercice-2-analyse-statistique-de-rendements-de-cryptomonnaie" class="nav-link" data-scroll-target="#exercice-2-analyse-statistique-de-rendements-de-cryptomonnaie">Exercice 2 : Analyse statistique de rendements de cryptomonnaie</a></li>
  <li><a href="#exercice-3-test-multivarié-vitesse-de-détection-en-grande-dimension" id="toc-exercice-3-test-multivarié-vitesse-de-détection-en-grande-dimension" class="nav-link" data-scroll-target="#exercice-3-test-multivarié-vitesse-de-détection-en-grande-dimension">Exercice 3 : Test multivarié — vitesse de détection en grande dimension</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">TD5 : Exercices complémentaires</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="exercice-1-loi-binomiale-négative-contrôle-qualité" class="level2">
<h2 class="anchored" data-anchor-id="exercice-1-loi-binomiale-négative-contrôle-qualité">Exercice 1 : Loi binomiale négative — Contrôle qualité</h2>
<p>Une usine fabrique des composants électroniques. Un protocole de contrôle qualité consiste à tester les pièces une par une, séquentiellement, jusqu’à trouver un nombre fixé <span class="math inline">\(r\)</span> de pièces défectueuses. On note <span class="math inline">\(X\)</span> le nombre total de pièces testées au moment où la <span class="math inline">\(r\)</span>-ème pièce défectueuse est trouvée.</p>
<p>On rappelle que <span class="math inline">\(X\)</span> suit une loi <strong>binomiale négative</strong> <span class="math inline">\(\mathrm{NegBin}(r, p)\)</span>, où <span class="math inline">\(p\)</span> est la probabilité qu’une pièce soit défectueuse. Sa loi est : <span class="math display">\[
P(X = n) = \binom{n-1}{r-1} p^r (1-p)^{n-r}, \quad n = r,\, r+1,\, r+2, \dots
\]</span></p>
<ol type="1">
<li><p>Montrer que <span class="math inline">\(\mathbb{E}[X] = \frac{r}{p}\)</span> et <span class="math inline">\(\mathbb{V}(X) = \frac{r(1-p)}{p^2}\)</span>.</p>
<p><em>Indication : écrire <span class="math inline">\(X = Y_1 + \cdots + Y_r\)</span> où les <span class="math inline">\(Y_i\)</span> sont i.i.d. de loi géométrique <span class="math inline">\(\mathcal G(p)\)</span>.</em></p></li>
<li><p>Montrer que la famille <span class="math inline">\(\{\mathrm{NegBin}(r, p) : p \in (0,1)\}\)</span> (avec <span class="math inline">\(r\)</span> fixé) est une famille exponentielle en identifiant les fonctions <span class="math inline">\(a(n)\)</span>, <span class="math inline">\(b(p)\)</span>, <span class="math inline">\(c(p)\)</span> et <span class="math inline">\(d(n)\)</span> telles que : <span class="math display">\[
P(X = n) = a(n)\, b(p)\, \exp\!\bigl(c(p)\, d(n)\bigr).
\]</span></p></li>
<li><p>Le fabricant garantit un taux de défaut d’au plus <span class="math inline">\(p_0\)</span>. On veut tester : <span class="math display">\[
H_0 : p \leq p_0 \quad \text{contre} \quad H_1 : p &gt; p_0.
\]</span> En utilisant le théorème de Karlin–Rubin (théorème 5 du cours), montrer que le test UMP au niveau <span class="math inline">\(\alpha\)</span> rejette <span class="math inline">\(H_0\)</span> pour les petites valeurs de <span class="math inline">\(X\)</span>.</p>
<p><em>Interpréter : pourquoi observe-t-on peu de pièces testées quand le taux de défaut est élevé ?</em></p></li>
<li><p><strong>Dualité binomiale négative–binomiale.</strong> Montrer que pour tout <span class="math inline">\(n \geq r\)</span> : <span class="math display">\[
P_{p}(X \leq n) = P(Y \geq r) \quad \text{où} \quad Y \sim \mathrm{Bin}(n, p).
\]</span> <em>Indication : interpréter les deux événements. <span class="math inline">\(\{X \leq n\}\)</span> signifie « au moins <span class="math inline">\(r\)</span> défauts parmi les <span class="math inline">\(n\)</span> premières pièces ». Comparer avec <span class="math inline">\(\{Y \geq r\}\)</span>.</em></p></li>
<li><p><strong>Application numérique.</strong> L’inspecteur fixe <span class="math inline">\(r = 19\)</span> et le fabricant garantit <span class="math inline">\(p_0 = 0{,}10\)</span>. Après avoir testé <span class="math inline">\(n = 100\)</span> pièces, l’inspecteur a trouvé ses <span class="math inline">\(19\)</span> pièces défectueuses.</p>
<ol type="a">
<li><p>En utilisant la question 4, exprimer la p-valeur en termes d’une loi binomiale.</p></li>
<li><p>Calculer la p-valeur approchée en utilisant le TCL appliqué à <span class="math inline">\(Y \sim \mathrm{Bin}(100,\, 0{,}10)\)</span>.</p>
<p><em>On rappelle que <span class="math inline">\(\Phi(3) \approx 0{,}9987\)</span>.</em></p></li>
<li><p>Conclure au niveau de signification <span class="math inline">\(\alpha = 0{,}01\)</span>.</p></li>
</ol></li>
<li><p><strong>Bonus : lien avec la loi Gamma.</strong> On rappelle que <span class="math inline">\(\mathcal G(p) = p \cdot \mathrm{NegBin}(1, p)\)</span> (en loi, à un facteur <span class="math inline">\(p\)</span> près). Montrer que si <span class="math inline">\(X_1 \sim \mathcal G(p)\)</span>, alors quand <span class="math inline">\(p \to 0\)</span> : <span class="math display">\[
p\, X_1 \xrightarrow{d} \mathcal E(1).
\]</span> En déduire que <span class="math inline">\(p \cdot \mathrm{NegBin}(r, p) \xrightarrow{d} \Gamma(r, 1)\)</span> quand <span class="math inline">\(p \to 0\)</span>.</p>
<p><em>C’est l’analogue discret-continu : la géométrique est la version discrète de l’exponentielle, et la binomiale négative est la version discrète de la Gamma.</em></p></li>
</ol>
</section>
<section id="exercice-2-analyse-statistique-de-rendements-de-cryptomonnaie" class="level2">
<h2 class="anchored" data-anchor-id="exercice-2-analyse-statistique-de-rendements-de-cryptomonnaie">Exercice 2 : Analyse statistique de rendements de cryptomonnaie</h2>
<p>Le <strong>Bitcoin</strong> (BTC) est une cryptomonnaie dont le prix est coté en continu. On note <span class="math inline">\(P_t\)</span> le prix de clôture à l’heure <span class="math inline">\(t\)</span>. Le <strong>rendement</strong> (ou <em>return</em>) horaire est défini par : <span class="math display">\[
R_t = \frac{P_t - P_{t-1}}{P_{t-1}},
\]</span> c’est-à-dire la variation relative du prix entre deux heures consécutives, exprimée en pourcentage. Par exemple, si le prix passe de <span class="math inline">\(100\)</span> à <span class="math inline">\(102\)</span>, le rendement est <span class="math inline">\(R = 2\%\)</span>.</p>
<p>Un analyste quantitatif dispose de rendements horaires du Bitcoin sur deux périodes distinctes :</p>
<ul>
<li><strong>Période haussière</strong> (<em>bull run</em>, janvier–mars 2024) : <span class="math inline">\(n_1 = 1776\)</span> rendements horaires,</li>
<li><strong>Période baissière</strong> (<em>bear market</em>, mai–août 2022) : <span class="math inline">\(n_2 = 2208\)</span> rendements horaires.</li>
</ul>
<p>Les statistiques descriptives (en pourcentage) sont résumées ci-dessous :</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Période haussière</th>
<th style="text-align: center;">Période baissière</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Taille <span class="math inline">\(n\)</span></td>
<td style="text-align: center;"><span class="math inline">\(1776\)</span></td>
<td style="text-align: center;"><span class="math inline">\(2208\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Moyenne empirique <span class="math inline">\(\overline R\)</span> (en %)</td>
<td style="text-align: center;"><span class="math inline">\(0{,}031\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-0{,}018\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Écart-type empirique <span class="math inline">\(\hat\sigma\)</span> (en %)</td>
<td style="text-align: center;"><span class="math inline">\(0{,}566\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0{,}877\)</span></td>
</tr>
</tbody>
</table>
<p>L’analyste dispose également des rendements horaires de l’<strong>Ethereum</strong> (ETH) sur les mêmes périodes, et a calculé les statistiques suivantes.</p>
<p><strong>Corrélations de Pearson :</strong></p>
<p>On note <span class="math inline">\(S_t = R_t^{\text{BTC}} - R_t^{\text{ETH}}\)</span> le <strong>spread</strong> entre les rendements du Bitcoin et de l’Ethereum.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 28%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Paire de variables</th>
<th style="text-align: left;">Période</th>
<th style="text-align: center;"><span class="math inline">\(r\)</span></th>
<th style="text-align: center;"><span class="math inline">\(n\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\((R_t^{\text{BTC}},\, R_{t+1}^{\text{BTC}})\)</span> — autocorrélation BTC</td>
<td style="text-align: left;">Bull</td>
<td style="text-align: center;"><span class="math inline">\(0{,}008\)</span></td>
<td style="text-align: center;"><span class="math inline">\(1775\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\((R_t^{\text{BTC}},\, R_{t+1}^{\text{BTC}})\)</span> — autocorrélation BTC</td>
<td style="text-align: left;">Bear</td>
<td style="text-align: center;"><span class="math inline">\(0{,}007\)</span></td>
<td style="text-align: center;"><span class="math inline">\(2207\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\((R_t^{\text{BTC}},\, R_t^{\text{ETH}})\)</span> — corrélation BTC/ETH</td>
<td style="text-align: left;">Bull</td>
<td style="text-align: center;"><span class="math inline">\(0{,}76\)</span></td>
<td style="text-align: center;"><span class="math inline">\(1776\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\((R_t^{\text{BTC}},\, R_t^{\text{ETH}})\)</span> — corrélation BTC/ETH</td>
<td style="text-align: left;">Bear</td>
<td style="text-align: center;"><span class="math inline">\(0{,}91\)</span></td>
<td style="text-align: center;"><span class="math inline">\(2208\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\((S_t,\, S_{t+1})\)</span> — autocorrélation du spread</td>
<td style="text-align: left;">Bull</td>
<td style="text-align: center;"><span class="math inline">\(-0{,}062\)</span></td>
<td style="text-align: center;"><span class="math inline">\(1775\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\((S_t,\, S_{t+1})\)</span> — autocorrélation du spread</td>
<td style="text-align: left;">Bear</td>
<td style="text-align: center;"><span class="math inline">\(-0{,}029\)</span></td>
<td style="text-align: center;"><span class="math inline">\(2207\)</span></td>
</tr>
</tbody>
</table>
<p><strong>Tests de normalité :</strong></p>
<ul>
<li>Test du <span class="math inline">\(\chi^2\)</span> d’adéquation à <span class="math inline">\(\mathcal N(\hat\mu, \hat\sigma^2)\)</span> avec <span class="math inline">\(m = 5\)</span> (soit <span class="math inline">\(12\)</span> intervalles) :</li>
</ul>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Série</th>
<th style="text-align: left;">Période</th>
<th style="text-align: center;"><span class="math inline">\(\chi^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(R^{\text{BTC}}\)</span></td>
<td style="text-align: left;">Bull</td>
<td style="text-align: center;"><span class="math inline">\(622{,}8\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(R^{\text{BTC}}\)</span></td>
<td style="text-align: left;">Bear</td>
<td style="text-align: center;"><span class="math inline">\(524{,}7\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(S = R^{\text{BTC}} - R^{\text{ETH}}\)</span></td>
<td style="text-align: left;">Bull</td>
<td style="text-align: center;"><span class="math inline">\(385{,}1\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(S = R^{\text{BTC}} - R^{\text{ETH}}\)</span></td>
<td style="text-align: left;">Bear</td>
<td style="text-align: center;"><span class="math inline">\(498{,}1\)</span></td>
</tr>
</tbody>
</table>
<p>On suppose que les rendements sont des réalisations de variables aléatoires gaussiennes i.i.d. au sein de chaque période, et que les deux échantillons sont indépendants.</p>
<p>Pour chaque question, on définira précisément <span class="math inline">\(H_0\)</span> et <span class="math inline">\(H_1\)</span> avec des notations mathématiques, on choisira le test adapté, on calculera la statistique de test et la p-valeur, et on conclura au niveau <span class="math inline">\(\alpha = 0{,}05\)</span>.</p>
<ol type="1">
<li><p>Le rendement moyen du BTC est-il significativement différent de <span class="math inline">\(0\)</span> en période bull ? En période bear ?</p></li>
<li><p>Le BTC a perdu environ <span class="math inline">\(40\%\)</span> de sa valeur sur la période bear (<span class="math inline">\(38\,000 \to 23\,000\)</span> USD). Comment expliquer que le test de la question 1 ne rejette pas <span class="math inline">\(H_0\)</span> en période bear ?</p></li>
<li><p>Le rendement d’une heure du BTC permet-il de prédire le rendement de l’heure suivante ? Répondre pour les deux périodes.</p></li>
<li><p>Les rendements du Bitcoin et de l’Ethereum évoluent-ils ensemble ? Répondre pour les deux périodes. Comment la corrélation évolue-t-elle entre bull et bear ? Interpréter.</p></li>
<li><p>Le spread <span class="math inline">\(S_t\)</span> est-il autocorrélé ? Répondre pour les deux périodes. Interpréter la différence avec la question 3.</p></li>
<li><p>Les rendements du BTC suivent-ils une loi gaussienne ? Justifier le nombre de degrés de liberté et conclure. Même question pour le spread <span class="math inline">\(S_t\)</span>. Ce résultat est-il surprenant pour des données financières ?</p></li>
<li><p>La volatilité du BTC est-elle la même dans les deux régimes de marché ?</p></li>
<li><p>Le rendement moyen du BTC diffère-t-il entre les deux périodes ? Justifier le choix du test.</p></li>
<li><p>L’analyste discrétise les rendements en quatre catégories et obtient le tableau de contingence suivant :</p>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;"><span class="math inline">\(R &lt; -1\%\)</span></th>
<th style="text-align: center;"><span class="math inline">\(-1\% \leq R &lt; 0\%\)</span></th>
<th style="text-align: center;"><span class="math inline">\(0\% \leq R &lt; 1\%\)</span></th>
<th style="text-align: center;"><span class="math inline">\(R \geq 1\%\)</span></th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Bull</td>
<td style="text-align: center;"><span class="math inline">\(53\)</span></td>
<td style="text-align: center;"><span class="math inline">\(803\)</span></td>
<td style="text-align: center;"><span class="math inline">\(848\)</span></td>
<td style="text-align: center;"><span class="math inline">\(72\)</span></td>
<td style="text-align: center;"><span class="math inline">\(1776\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Bear</td>
<td style="text-align: center;"><span class="math inline">\(188\)</span></td>
<td style="text-align: center;"><span class="math inline">\(951\)</span></td>
<td style="text-align: center;"><span class="math inline">\(908\)</span></td>
<td style="text-align: center;"><span class="math inline">\(161\)</span></td>
<td style="text-align: center;"><span class="math inline">\(2208\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Total</strong></td>
<td style="text-align: center;"><span class="math inline">\(241\)</span></td>
<td style="text-align: center;"><span class="math inline">\(1754\)</span></td>
<td style="text-align: center;"><span class="math inline">\(1756\)</span></td>
<td style="text-align: center;"><span class="math inline">\(233\)</span></td>
<td style="text-align: center;"><span class="math inline">\(3984\)</span></td>
</tr>
</tbody>
</table>
<p>La distribution des rendements est-elle la même dans les deux régimes ?</p></li>
<li><p>Comparer les conclusions des questions 7, 8 et 9. Que peut-on dire globalement sur la différence de comportement du Bitcoin entre les périodes haussière et baissière ?</p></li>
<li><p><strong>Test binomial.</strong> On compte le nombre de rendements horaires strictement positifs :</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Période</th>
<th style="text-align: center;">Rendements positifs</th>
<th style="text-align: center;"><span class="math inline">\(n\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Bull</td>
<td style="text-align: center;"><span class="math inline">\(920\)</span></td>
<td style="text-align: center;"><span class="math inline">\(1776\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Bear</td>
<td style="text-align: center;"><span class="math inline">\(1069\)</span></td>
<td style="text-align: center;"><span class="math inline">\(2208\)</span></td>
</tr>
</tbody>
</table>
<ol type="a">
<li><p>La proportion de rendements positifs est-elle significativement différente de <span class="math inline">\(50\%\)</span> en période bull ? En période bear ?</p></li>
<li><p>Comparer avec la conclusion de la question 1 (test de Student). Comment expliquer que le test binomial ne rejette pas alors que le test de Student rejette en période bull ?</p></li>
</ol></li>
<li><p><strong>Test de Wilcoxon.</strong> Les rendements du BTC et de l’ETH sont observés aux mêmes instants. On considère les différences <span class="math inline">\(D_t = R_t^{\text{BTC}} - R_t^{\text{ETH}}\)</span> et on observe :</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Période</th>
<th style="text-align: center;">Médiane de <span class="math inline">\(D_t\)</span> (en %)</th>
<th style="text-align: center;"><span class="math inline">\(n\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Bull</td>
<td style="text-align: center;"><span class="math inline">\(0{,}017\)</span></td>
<td style="text-align: center;"><span class="math inline">\(1776\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Bear</td>
<td style="text-align: center;"><span class="math inline">\(0{,}007\)</span></td>
<td style="text-align: center;"><span class="math inline">\(2208\)</span></td>
</tr>
</tbody>
</table>
<ol type="a">
<li><p>Effectuer un test des rangs signés de Wilcoxon sur les données appariées <span class="math inline">\((R_t^{\text{BTC}}, R_t^{\text{ETH}})\)</span> en période bull et en période bear.</p></li>
<li><p>On a vu à la question 4 que BTC et ETH sont très corrélés. Le test de Wilcoxon montre-t-il que leurs distributions sont différentes ? Interpréter.</p></li>
</ol></li>
<li><p>On a vu à la question 3 que les rendements <span class="math inline">\(R_t\)</span> et <span class="math inline">\(R_{t+1}\)</span> ne sont pas corrélés. On calcule maintenant les corrélations de Pearson sur les <strong>carrés</strong> des rendements :</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Paire de variables</th>
<th style="text-align: left;">Période</th>
<th style="text-align: center;"><span class="math inline">\(r\)</span></th>
<th style="text-align: center;"><span class="math inline">\(n\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\((R_t^2,\, R_{t+1}^2)\)</span></td>
<td style="text-align: left;">Bull</td>
<td style="text-align: center;"><span class="math inline">\(0{,}321\)</span></td>
<td style="text-align: center;"><span class="math inline">\(1775\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\((R_t^2,\, R_{t+1}^2)\)</span></td>
<td style="text-align: left;">Bear</td>
<td style="text-align: center;"><span class="math inline">\(0{,}292\)</span></td>
<td style="text-align: center;"><span class="math inline">\(2207\)</span></td>
</tr>
</tbody>
</table>
<ol type="a">
<li><p>Tester si <span class="math inline">\(R_t^2\)</span> et <span class="math inline">\(R_{t+1}^2\)</span> sont corrélés, en période bull et en période bear.</p></li>
<li><p>Comment interpréter ce résultat ? Que signifie-t-il sur la volatilité du Bitcoin ?</p></li>
<li><p>Les rendements <span class="math inline">\(R_t\)</span> et <span class="math inline">\(R_{t+1}\)</span> sont-ils indépendants ? Justifier.</p></li>
</ol></li>
<li><p><strong>Haute fréquence.</strong> On dispose maintenant de <span class="math inline">\(n = 14\,400\)</span> rendements <strong>à la minute</strong> du BTC et de l’ETH sur <span class="math inline">\(10\)</span> jours. On calcule l’autocorrélation du spread <span class="math inline">\(S_t = R_t^{\text{BTC}} - R_t^{\text{ETH}}\)</span> à différents décalages (<em>lags</em>) :</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Lag <span class="math inline">\(1\)</span> min</th>
<th style="text-align: center;">Lag <span class="math inline">\(2\)</span> min</th>
<th style="text-align: center;">Lag <span class="math inline">\(5\)</span> min</th>
<th style="text-align: center;">Lag <span class="math inline">\(30\)</span> min</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Spread <span class="math inline">\(S_t\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-0{,}026\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-0{,}027\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-0{,}003\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-0{,}000\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">BTC <span class="math inline">\(R_t\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-0{,}007\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-0{,}019\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-0{,}006\)</span></td>
<td style="text-align: center;"><span class="math inline">\(+0{,}029\)</span></td>
</tr>
</tbody>
</table>
<p>(<span class="math inline">\(n \approx 14\,400\)</span> pour chaque test.)</p>
<ol type="a">
<li><p>Tester si le spread est autocorrélé au lag <span class="math inline">\(1\)</span> min et au lag <span class="math inline">\(5\)</span> min.</p></li>
<li><p>Même question pour le BTC seul au lag <span class="math inline">\(1\)</span> min et au lag <span class="math inline">\(2\)</span> min.</p></li>
<li><p>Le signe de la corrélation du spread aux lags <span class="math inline">\(1\)</span> et <span class="math inline">\(2\)</span> min est négatif. Qu’est-ce que cela signifie pour le comportement du spread à court terme ?</p></li>
<li><p>Comparer l’autocorrélation du spread et du BTC seul au lag <span class="math inline">\(1\)</span> min. Comment expliquer que le spread ait une autocorrélation plus forte ?</p></li>
</ol></li>
</ol>
</section>
<section id="exercice-3-test-multivarié-vitesse-de-détection-en-grande-dimension" class="level2">
<h2 class="anchored" data-anchor-id="exercice-3-test-multivarié-vitesse-de-détection-en-grande-dimension">Exercice 3 : Test multivarié — vitesse de détection en grande dimension</h2>
<p>On observe un vecteur gaussien <span class="math inline">\(X = (X_1, \ldots, X_p) \in \mathbb{R}^p\)</span> dont les coordonnées sont indépendantes, <span class="math inline">\(X_j \sim \mathcal{N}(\theta_j, 1)\)</span>. Le paramètre inconnu est <span class="math inline">\(\theta = (\theta_1, \ldots, \theta_p) \in \mathbb{R}^p\)</span>.</p>
<p>On veut tester l’hypothèse “rien ne se passe” contre l’hypothèse “au moins une coordonnée porte un signal au moins <span class="math inline">\(\rho\)</span>” : <span class="math display">\[
H_0 : \theta = 0 \qquad \text{contre} \qquad H_1(\rho) : \|\theta\|_\infty \geq \rho,
\]</span> où <span class="math inline">\(\|\theta\|_\infty = \max_{1 \leq j \leq p} |\theta_j|\)</span> et <span class="math inline">\(\rho &gt; 0\)</span>.</p>
<p>L’objectif est de comprendre comment la dimension <span class="math inline">\(p\)</span> affecte la séparation minimale <span class="math inline">\(\rho\)</span> détectable. On considère le test “naturel” basé sur la norme infinie de l’observation : <span class="math display">\[
T(X) = \mathbf{1}\bigl\{\|X\|_\infty &gt; t\bigr\}, \qquad \|X\|_\infty = \max_{1 \leq j \leq p} |X_j|,
\]</span> où <span class="math inline">\(t &gt; 0\)</span> est un seuil à choisir. Le risque s’écrit <span class="math display">\[
R(T, \rho) = \mathbb{P}_0\bigl(\|X\|_\infty &gt; t\bigr) + \sup_{\|\theta\|_\infty \geq \rho} \mathbb{P}_\theta\bigl(\|X\|_\infty \leq t\bigr).
\]</span></p>
<ol type="1">
<li><p><strong>Erreur de 1ère espèce.</strong> En utilisant l’union bound et la majoration de la queue gaussienne <span class="math inline">\(1 - \Phi(t) \leq e^{-t^2/2}\)</span> pour <span class="math inline">\(t &gt; 0\)</span>, montrer que : <span class="math display">\[
\mathbb{P}_0\bigl(\|X\|_\infty &gt; t\bigr) \leq 2p\, e^{-t^2/2}.
\]</span></p></li>
<li><p><strong>Erreur de 2nde espèce.</strong> Soit <span class="math inline">\(\theta \in \mathbb{R}^p\)</span> avec <span class="math inline">\(\|\theta\|_\infty \geq \rho\)</span>. Montrer que pour tout <span class="math inline">\(t \in (0, \rho)\)</span> : <span class="math display">\[
\mathbb{P}_\theta\bigl(\|X\|_\infty \leq t\bigr) \leq e^{-(\rho - t)^2/2}.
\]</span></p>
<p><em>Indication : choisir <span class="math inline">\(j^*\)</span> tel que <span class="math inline">\(|\theta_{j^*}| \geq \rho\)</span> et majorer <span class="math inline">\(\mathbb{P}_\theta(\|X\|_\infty \leq t)\)</span> par <span class="math inline">\(\mathbb{P}_\theta(|X_{j^*}| \leq t)\)</span>.</em></p></li>
<li><p><strong>Choix du seuil et borne supérieure minimax.</strong> Soit <span class="math inline">\(\beta \in (0, 1)\)</span>. Choisissant <span class="math inline">\(t = \sqrt{2 \log(4p/\beta)}\)</span>, montrer que pour tout <span class="math inline">\(\rho \geq 2t\)</span> : <span class="math display">\[
R(T, \rho) \leq \beta.
\]</span></p>
<p>En déduire que le risque minimax vérifie <span class="math inline">\(R^*(\rho) \leq \beta\)</span> dès que <span class="math display">\[
\rho \;\geq\; 2\sqrt{2 \log(4p/\beta)}.
\]</span> En d’autres termes, la vitesse de séparation minimax satisfait <span class="math display">\[
\rho^*_{\min}(p) \;\lesssim\; \sqrt{\log p}.
\]</span></p></li>
<li><p><strong>Comparaison.</strong> Pour <span class="math inline">\(p = 1\)</span>, on a vu en cours que <span class="math inline">\(\rho^*_{\min} \asymp 1\)</span>. Quel est le coût (en <span class="math inline">\(\rho\)</span>) de tester en dimension <span class="math inline">\(p\)</span> par rapport à la dimension <span class="math inline">\(1\)</span> ? Le résultat est-il surprenant compte tenu de la correction de Bonferroni ?</p></li>
<li><p><strong>Bonus : borne inférieure.</strong> On veut montrer que le test de la question 3 est essentiellement optimal : <span class="math display">\[
\rho^*_{\min}(p) \;\gtrsim\; \sqrt{\log p}.
\]</span></p>
<p>On utilise une borne inférieure bayésienne. Soit <span class="math inline">\(\pi\)</span> la loi uniforme sur les <span class="math inline">\(2p\)</span> vecteurs <span class="math inline">\(\{\pm \rho\, e_j : j = 1, \ldots, p\}\)</span>, où <span class="math inline">\(e_j\)</span> désigne le <span class="math inline">\(j\)</span>-ème vecteur de la base canonique de <span class="math inline">\(\mathbb{R}^p\)</span>. Notons <span class="math inline">\(f_0\)</span> la densité de <span class="math inline">\(\mathcal{N}(0, I_p)\)</span> et <span class="math display">\[
f_\pi(x) = \frac{1}{2p} \sum_{j=1}^p \bigl(f_{\rho e_j}(x) + f_{-\rho e_j}(x)\bigr)
\]</span> la densité du mélange.</p>
<ol type="a">
<li><p>Montrer que pour tout test <span class="math inline">\(T\)</span> : <span class="math display">\[
R(T, \rho) \geq \int T\, f_0\, dx + \int (1-T)\, f_\pi\, dx \geq \int \min(f_0, f_\pi)\, dx.
\]</span></p></li>
<li><p>Montrer que <span class="math display">\[
\frac{f_{\theta}(x)}{f_0(x)} = \exp\!\Bigl(\theta^\top x - \tfrac{1}{2}\|\theta\|^2\Bigr) \quad \text{et} \quad \mathbb{E}_0\!\bigl[e^{\rho X_j}\bigr] = e^{\rho^2/2}.
\]</span> En déduire que <span class="math display">\[
\chi^2(f_\pi, f_0) := \int \frac{f_\pi^2}{f_0}\, dx - 1 = \frac{\cosh(\rho^2) - 1}{p}.
\]</span></p></li>
<li><p>En déduire que pour <span class="math inline">\(\rho^2 = c \log p\)</span> avec <span class="math inline">\(c &lt; 1\)</span>, on a <span class="math inline">\(\chi^2(f_\pi, f_0) \to 0\)</span> quand <span class="math inline">\(p \to \infty\)</span>.</p></li>
<li><p>En utilisant l’inégalité (admise) <span class="math display">\[
\int \min(f_0, f_\pi)\, dx \;\geq\; 1 - \tfrac{1}{2}\sqrt{\chi^2(f_\pi, f_0)},
\]</span> conclure que <span class="math inline">\(\rho^*_{\min}(p) \gtrsim \sqrt{\log p}\)</span>.</p></li>
</ol>
<p><em>Conclusion : pour le test en norme infinie en dimension <span class="math inline">\(p\)</span>, la vitesse minimax exacte est <span class="math inline">\(\rho^*_{\min}(p) \asymp \sqrt{\log p}\)</span>. La dimension n’entre que <strong>logarithmiquement</strong> dans le seuil de détection — c’est une nouvelle illustration du phénomène déjà rencontré avec la correction de Bonferroni.</em></p></li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>