<!DOCTYPE html>
<html lang="en"><head>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-7b4406b7675125bc2ba204020e191172.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.22">

  <title>Emmanuel Pilliat – Counting Models</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../../../site_libs/revealjs/dist/theme/quarto-a9356234971a534880724c4687078043.css">
  <link rel="stylesheet" href="../../../styles.css">
  <link href="../../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Counting Models</h1>

<div class="quarto-title-authors">
</div>

</section>
<section class="slide level2">

<p><span class="math inline">\(\newcommand{\VS}{\quad \mathrm{VS} \quad}\)</span> <span class="math inline">\(\newcommand{\and}{\quad \mathrm{and} \quad}\)</span> <span class="math inline">\(\newcommand{\E}{\mathbb E}\)</span> <span class="math inline">\(\newcommand{\P}{\mathbb P}\)</span> <span class="math inline">\(\newcommand{\Var}{\mathbb V}\)</span> <span class="math inline">\(\newcommand{\Cov}{\mathrm{Cov}}\)</span> <span class="math inline">\(\newcommand{\1}{\mathbf 1}\)</span></p>
</section>
<section>
<section id="log-linear-poisson-model" class="title-slide slide level1 center">
<h1>Log-Linear Poisson Model</h1>

</section>
<section id="model-assumption" class="slide level2">
<h2>Model Assumption</h2>
<div class="fragment">
<p>We assume that</p>
<div class="square-def">
<p><span class="math display">\[Y_i|X_i=x_i \sim P(\lambda_\beta(x_i))\quad \text{with} \quad \lambda_\beta(x) = \exp(x^T \beta)\]</span></p>
</div>
<p>with <span class="math inline">\(\lambda_\beta(x) = \exp(x^T \beta)\)</span>.</p>
</div>
<div class="fragment">
<p>In particular, <span style="background-color: lightblue;"><span class="math inline">\(\mathbb E[Y_i|X_i=x_i] = \lambda_\beta(x)\)</span></span></p>
</div>
<div class="fragment">
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><span class="math inline">\(Y|X\)</span> follows a Poisson distribution but not <span class="math inline">\(Y\)</span> if <span class="math inline">\(X\)</span> is random!</p>
<p>(We can only say that it is a mixture of Poisson)</p>
</div>
</div>
</div>
</div>
</section>
<section id="illustration" class="slide level2">
<h2>Illustration</h2>
<div class="fragment">
<p><strong>Example</strong>: binary regressor <span class="math inline">\(X\)</span> (with as many <span class="math inline">\(X = 0\)</span> as <span class="math inline">\(X = 1\)</span>)</p>
</div>
<div class="fragment">
<div class="square-def">
<p><span class="math inline">\(Y|(X = 0) \sim P(2) \and Y|(X = 1) \sim P(10)\)</span></p>
</div>
<p><img data-src="../images/poisson_mix.png" style="width:90.0%"></p>
</div>
</section>
<section id="rate-ratio" class="slide level2">
<h2>Rate Ratio</h2>
<div class="fragment">
<p>There is <span style="background-color: orange;">no notion of OR</span> since we are not estimating a probability (or a probability ratio) but an expectation.</p>
</div>
<div class="fragment">
<p>The equivalent notion here is the <span style="background-color: lightgreen;">rate ratio (RR)</span>, <span class="math inline">\(\lambda(x)\)</span> being seen as an average rate of occurrence of <span class="math inline">\(Y\)</span>.</p>
</div>
<div class="fragment">
<p>For two characteristics <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>, the rate ratio is simply:</p>
<div class="square-def">
<p><span class="math display">\[RR(x_1, x_2) = \frac{\lambda_\beta(x_1)}{\lambda_\beta(x_2)} = \exp((x_1 - x_2)^T \beta)\]</span></p>
</div>
</div>
</section>
<section id="particular-cases-for-rate-ratio" class="slide level2">
<h2>Particular Cases for Rate Ratio</h2>
<div class="fragment">
<p><strong>Single Regressor Difference</strong>: If <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span> differ only by regressor <span class="math inline">\(j\)</span>:</p>
<p><span style="background-color: lightblue;"><span class="math inline">\(RR(x_1, x_2) = \exp((x_{1j} - x_{2j})\beta_j)\)</span></span></p>
</div>
<div class="fragment">
<p><strong>Binary regressor</strong>: (<span class="math inline">\(x_{1j} = 1\)</span> and <span class="math inline">\(x_{2j} = 0\)</span>): <span style="background-color: lightblue;"><span class="math inline">\(RR_j = e^{\beta_j}\)</span></span>.</p>
</div>
</section>
<section id="log-likelihood" class="slide level2">
<h2>Log-Likelihood</h2>
<div class="fragment">
<div class="square-def">
<p><span class="math display">\[P(Y = k|X = x) = e^{-\lambda_\beta(x)} \frac{\lambda_\beta(x)^k}{k!}\]</span></p>
</div>
</div>
<div class="fragment">
<p>Thus the <span style="background-color: yellow;">sample likelihood</span> equals <span style="background-color: lightblue;"><span class="math inline">\(\prod_{i=1}^n e^{-\lambda_\beta(x_i)} \frac{\lambda_\beta(x_i)^{y_i}}{y_i!}\)</span></span></p>
</div>
<div class="fragment">
<p>Since <span class="math inline">\(\lambda_\beta(x) = \exp(x^T \beta)\)</span>, the <span style="background-color: yellow;">log-likelihood</span> therefore equals</p>
<div class="square-def">
<p><span class="math display">\[L = \sum_{i=1}^n \left[y_i x_i^T \beta - e^{x_i^T \beta} - \ln(y_i!)\right]\]</span></p>
</div>
</div>
</section>
<section id="estimation-of-beta-by-mle" class="slide level2">
<h2>Estimation of <span class="math inline">\(\beta\)</span> by MLE</h2>
<div class="fragment">
<p>By setting the gradient with respect to <span class="math inline">\(\beta\)</span> to zero, we find that the MLE <span class="math inline">\(\hat{\beta}\)</span> must verify:</p>
<div class="square-def">
<p><span class="math display">\[\sum_{i=1}^n y_i x_i = \sum_{i=1}^n \lambda_{\hat{\beta}}(x_i) x_i\]</span></p>
</div>
</div>
<div class="fragment">
<p>This is a system with <span class="math inline">\(p\)</span> unknowns (recall that <span style="background-color: orange;"><span class="math inline">\(x_i \in \mathbb R^p\)</span></span>) that we <span style="background-color: yellow;">solve numerically</span>.</p>
</div>
</section>
<section id="properties-of-hat-beta" class="slide level2">
<h2>Properties of <span class="math inline">\(\hat \beta\)</span></h2>
<div class="fragment">
<p>Under regularity conditions, when <span class="math inline">\(n \to \infty\)</span>:</p>
<div class="square-def">
<p><span class="math display">\[\hat{\beta} \sim N(\beta, (X^T W_{\hat{\beta}} X)^{-1})\]</span></p>
</div>
<p>where <span class="math inline">\(W_{\hat{\beta}} = \text{diag}(\lambda_{\hat{\beta}}(x_1), \ldots, \lambda_{\hat{\beta}}(x_n))\)</span>.</p>
</div>
<div class="fragment">
<p>We can therefore perform <span style="background-color: yellow;">Wald significance tests</span>.</p>
</div>
</section>
<section id="validation-deviance" class="slide level2">
<h2>Validation: Deviance</h2>
<div class="fragment">
<p>The <span style="background-color: yellow;">saturated model</span> (one parameter per different observation) leads to</p>
<div class="square-def">
<p><span class="math display">\[\hat{\lambda}(x) = \frac{y_x}{n_x}\]</span></p>
</div>
<ul>
<li class="fragment"><span style="background-color: lightblue;"><span class="math inline">\(y_x = \sum_{i:x_i=x} y_i\)</span></span> is the total number of <span class="math inline">\(Y\)</span> observed for characteristic <span class="math inline">\(x\)</span> on the sample</li>
<li class="fragment"><span style="background-color: lightblue;"><span class="math inline">\(n_x = \sum_{i:x_i=x} 1\)</span></span> is the number of times <span class="math inline">\(x\)</span> was observed.</li>
</ul>
</div>
</section>
<section id="saturated-log-likelihood" class="slide level2">
<h2>Saturated Log-Likelihood</h2>
<div class="fragment">
<p>The log-likelihood of the saturated model therefore equals:</p>
<div class="square-def">
<p><span class="math display">\[L_{\text{sat}} = \sum_x \left[y_x \ln\left(\frac{y_x}{n_x}\right) - y_x\right] - \text{cste}\]</span></p>
</div>
<p>where <span class="math inline">\(\text{cste} = \sum_{i=1}^n \ln(y_i!)\)</span>.</p>
</div>
</section>
<section id="deviance-formula" class="slide level2">
<h2>Deviance Formula</h2>
<div class="fragment">
<p>Thus the deviance equals</p>
<div style="font-size: 80%;">
<div class="square-def">
<p><span class="math display">\[D = 2(L_{\text{sat}} - L_{\text{mod}}) = 2\sum_x y_x \ln\left(\frac{y_x}{n_x \lambda_{\hat{\beta}}(x)}\right) - (y_x - n_x \lambda_{\hat{\beta}}(x))\]</span></p>
</div>
</div>
</div>
<div class="fragment">
<p><span style="background-color: yellow;">If a constant is in the model</span> (one coordinate of <span class="math inline">\(x\)</span> equals <span class="math inline">\(1\)</span>), we have from the likelihood equations <span class="math inline">\(\sum_x y_x = \sum_x n_x \lambda_{\hat{\beta}}(x)\)</span> and then</p>
<div style="font-size: 80%;">
<div class="square-def">
<p><span class="math display">\[D = 2\sum_x y_x \ln\left(\frac{y_x}{\hat{y}_x}\right)\]</span></p>
</div>
</div>
<p>where <span class="math inline">\(\hat{y}_x = n_x \lambda_{\hat{\beta}}(x)\)</span> are the expected theoretical counts.</p>
</div>
</section>
<section id="validation-deviance-test" class="slide level2">
<h2>Validation: Deviance Test</h2>
<div class="fragment">
<p>As in logistic regression, we can <span style="background-color: yellow;">compare two nested models by a deviance test</span> (or likelihood ratio test)</p>
</div>
<div class="fragment">
<p>If <span style="background-color: yellow;">model 2 has <span class="math inline">\(q\)</span> fewer</span> parameters compared to model 1, we have under <span class="math inline">\(H_0\)</span>: “the <span class="math inline">\(q\)</span> coefficients in question are zero”:</p>
<div class="square-def">
<p><span class="math display">\[D_2 - D_1 = 2(L_1 - L_2) \xrightarrow{L} \chi^2_q\]</span></p>
</div>
<p>Rejection region at level <span class="math inline">\(\alpha\)</span>:</p>
<div class="square-def">
<p><span class="math display">\[\text{CR}_\alpha = \{D_2 - D_1 &gt; \chi^2_q(1-\alpha)\}\]</span></p>
</div>
</div>
</section>
<section id="global-significance-test" class="slide level2">
<h2>Global Significance Test</h2>
<div class="fragment">
<p>The global significance test corresponds to the case where model 2 contains only the constant.</p>
</div>
<div class="fragment">
<p>In this case <span style="background-color: lightblue;"><span class="math inline">\(D_2 = D_0\)</span></span> and <span style="background-color: lightblue;"><span class="math inline">\(q = p - 1\)</span></span>.</p>
</div>
</section>
<section id="validation-graphical-inspection" class="slide level2">
<h2>Validation: Graphical Inspection</h2>
<div class="fragment">
<p>Plot the predicted counts <span style="background-color: lightblue;"><span class="math inline">\(\hat{y}_x = n_x \lambda_{\hat{\beta}}(x)\)</span></span> against the observed counts <span style="background-color: lightblue;"><span class="math inline">\(y_x\)</span></span>.</p>
</div>
<div class="fragment">
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>the predicted counts <span class="math inline">\(\hat{y}_x\)</span> represent the expectation of <span style="background-color: orange;">the expected counts given <span class="math inline">\(x\)</span></span>.</p>
<p>It is therefore normal that the observed counts <span style="background-color: orange;"><span class="math inline">\(y_x\)</span> are dispersed around the <span class="math inline">\(\hat{y}_x\)</span></span></p>
</div>
</div>
</div>
</div>
<div class="fragment">
<p>It is appropriate to have sufficiently large “classes” <span class="math inline">\(x\)</span> (<span style="background-color: lightblue;"><span class="math inline">\(n_x &gt; 5\)</span></span>) for the graph to be relevant.</p>
</div>
</section>
<section id="alternative-graphical-validation" class="slide level2">
<h2>Alternative Graphical Validation</h2>
<div class="fragment">
<p><strong>Idea</strong>: empirical distribution of <span class="math inline">\(Y\)</span> VS its predicted distribution.</p>
</div>
<div class="fragment">
<p>The <span style="background-color: yellow;">empirical distribution of <span class="math inline">\(Y\)</span></span> is simply given by</p>
<div class="square-def">
<p><span class="math inline">\(p_k = \frac{1}{n}\sum_{i=1}^n \mathbf{1}_{y_i = k}, \quad k \in \mathbb{N}\)</span></p>
</div>
</div>
<div class="fragment">
<p>While its predicted distribution is given by</p>
<div class="square-def">
<p><span class="math inline">\(\hat{p}_k = \frac{1}{n}\sum_{i=1}^n \hat{P}(Y = k|X = x_i), \quad k \in \mathbb{N}\)</span></p>
</div>
</div>
<div class="fragment">
<p>where <span class="math inline">\(\hat{P}(Y = k|X = x_i)\)</span> is the poisson distribution <span class="math inline">\(\mathcal P(\lambda_{\hat{\beta}}(x_i))\)</span>, i.e., <span style="background-color: lightblue;"><span class="math inline">\(\hat{P}(Y = k|X = x_i) = \frac{\lambda_{\hat{\beta}}(x_i)^k e^{-\lambda_{\hat{\beta}}(x_i)}}{k!}\)</span></span></p>
</div>
</section>
<section id="example-number-of-plant-species" class="slide level2">
<h2>Example: Number of Plant Species</h2>
<div class="fragment">
<p>Number of plant species recorded on a plot according to soil pH (Neutral, Acidic or Basic) and biomass collected.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Species</th>
<th>pH</th>
<th>Biomass</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>14</td>
<td>low</td>
<td>3.538</td>
</tr>
<tr class="even">
<td>31</td>
<td>mid</td>
<td>0.740</td>
</tr>
<tr class="odd">
<td>36</td>
<td>high</td>
<td>7.242</td>
</tr>
<tr class="even">
<td>20</td>
<td>mid</td>
<td>3.216</td>
</tr>
<tr class="odd">
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
</tbody>
</table>
</div>
<div class="fragment">
<p>We want to model <span class="math inline">\(Y =\)</span> “Species” as a <span style="background-color: yellow;">function of pH and Biomass</span>.</p>
</div>
</section>
<section id="example-r-output" class="slide level2">
<h2>Example: R output</h2>
<div class="fragment">
<div class="sourceCode" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a><span class="fu">glm</span>(Species ∼ pH <span class="sc">+</span> Biomass, <span class="at">family=</span>poisson)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="fragment">
<div style="font-size: 60%;">
<table class="caption-top">
<colgroup>
<col style="width: 19%">
<col style="width: 14%">
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Estimate</th>
<th>Std. Error</th>
<th>z value</th>
<th>Pr(&gt;</th>
<th>z</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td>3.84894</td>
<td>0.05281</td>
<td>72.885</td>
<td>&lt; 2e-16</td>
<td>***</td>
</tr>
<tr class="even">
<td>pHlow</td>
<td>-1.13639</td>
<td>0.06720</td>
<td>-16.910</td>
<td>&lt; 2e-16</td>
<td>***</td>
</tr>
<tr class="odd">
<td>pHmid</td>
<td>-0.44516</td>
<td>0.05486</td>
<td>-8.114</td>
<td>4.88e-16</td>
<td>***</td>
</tr>
<tr class="even">
<td>Biomass</td>
<td>-0.12756</td>
<td>0.01014</td>
<td>-12.579</td>
<td>&lt; 2e-16</td>
<td>***</td>
</tr>
</tbody>
</table>
<p>Signif. codes: 0 ‘<em><strong>’ 0.001 ’</strong>’ 0.01 ’</em>’ 0.05 ‘.’ 0.1 ’ ’ 1</p>
<p>(Dispersion parameter for poisson family taken to be 1)</p>
<p>Null deviance: 452.346<br>
Residual deviance: 99.242<br>
AIC: 526.43</p>
</div>
</div>
</section>
<section id="example-number-of-plant-species-1" class="slide level2">
<h2>Example: Number of Plant Species</h2>
<div class="fragment">
<p>Thus, the average number of species, given pH and Biomass, is estimated as</p>
<div style="font-size: 80%;">
<p><span style="background-color: lightblue;"><span class="math inline">\(\lambda_{\hat{\beta}}(\text{pH}, \text{Biomass}) = \exp(3.85 - 1.14 \mathbf{1}_{\text{pH=low}} - 0.46 \mathbf{1}_{\text{pH=mid}} - 0.13 \text{Biomass})\)</span></span></p>
</div>
</div>
<div class="fragment">
<p>Rate Ratio for low pH (acidic) compared to high pH (basic):</p>
<div style="font-size: 80%;">
<p><span style="background-color: lightblue;"><span class="math inline">\(RR(\text{acidic}, \text{basic}) = \exp(-1.14) = 0.32\)</span></span></p>
</div>
</div>
<div class="fragment">
<p>On average, there are therefore about <span style="background-color: yellow;">3 times fewer</span> species in acidic soil than in basic soil.</p>
</div>
</section>
<section id="example-interraction-ph-biomass" class="slide level2">
<h2>Example: Interraction Ph-Biomass</h2>
<div class="fragment">
<p>We can try to introduce an interaction between pH and Biomass</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a></a><span class="fu">glm</span>(Species <span class="sc">~</span> pH <span class="sc">+</span> Biomass <span class="sc">+</span> pH<span class="sc">:</span>Biomass, <span class="at">family=</span>poisson)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div style="font-size: 60%;">
<table class="caption-top">
<colgroup>
<col style="width: 19%">
<col style="width: 14%">
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Estimate</th>
<th>Std. Error</th>
<th>z value</th>
<th>Pr(&gt;</th>
<th>z</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td>3.76812</td>
<td>0.06153</td>
<td>61.240</td>
<td>&lt; 2e-16</td>
<td>***</td>
</tr>
<tr class="even">
<td>pHlow</td>
<td>-0.81557</td>
<td>0.10284</td>
<td>-7.931</td>
<td>2.18e-15</td>
<td>***</td>
</tr>
<tr class="odd">
<td>pHmid</td>
<td>-0.33146</td>
<td>0.09217</td>
<td>-3.596</td>
<td>0.000323</td>
<td>***</td>
</tr>
<tr class="even">
<td>Biomass</td>
<td>-0.10713</td>
<td>0.01249</td>
<td>-8.577</td>
<td>&lt; 2e-16</td>
<td>***</td>
</tr>
<tr class="odd">
<td>pHlow:Biomass</td>
<td>-0.15503</td>
<td>0.04003</td>
<td>-3.873</td>
<td>0.000108</td>
<td>***</td>
</tr>
<tr class="even">
<td>pHmid:Biomass</td>
<td>-0.03189</td>
<td>0.02308</td>
<td>-1.382</td>
<td>0.166954</td>
<td></td>
</tr>
</tbody>
</table>
<p>Signif. codes: 0 ‘<em><strong>’ 0.001 ’</strong>’ 0.01 ’</em>’ 0.05 ‘.’ 0.1 ’ ’ 1</p>
<p>(Dispersion parameter for poisson family taken to be 1)</p>
<p>Null deviance: 452.346<br>
Residual deviance: 83.201<br>
AIC: 514.39</p>
</div>
</div>
</section>
<section id="example-model-comparison" class="slide level2">
<h2>Example: Model Comparison</h2>
<div class="fragment">
<p>The model with <span style="background-color: yellow;">interaction seems preferable</span> (via AIC and deviance test).</p>
</div>
<div class="fragment">
<p>The average number of species, given pH and Biomass, is this time:</p>
<div style="font-size: 80%;">
<div class="square-def">
<p><span class="math display">\[\begin{aligned}
\lambda_{\hat{\beta}}(\text{pH}, \text{Bm}) &amp;= \exp(3.77 - 0.82 \mathbf{1}_{\text{pH=low}} - 0.33 \mathbf{1}_{\text{pH=mid}}) \\
&amp;- 0.11\text{Bm} - 0.16\text{Bm}\mathbf{1}_{\text{pH=low}} - 0.032\text{Bm}\mathbf{1}_{\text{pH=mid}}
\end{aligned}\]</span></p>
</div>
</div>
</div>
</section>
<section id="example-bm-dependent-rr" class="slide level2">
<h2>Example: Bm-dependent RR</h2>
<div class="fragment">
<p>The Rate Ratio for low pH (acidic) compared to high pH (basic) depends on Biomass and equals:</p>
<div style="font-size: 80%;">
<div class="square-def">
<p><span class="math inline">\(RR(\text{acidic}, \text{basic}) = \exp(-0.82 - 0.16\text{Bm})\)</span></p>
</div>
</div>
<div style="text-align: center;">
<p><img data-src="../images/biomass_interraction.png" style="width:40.0%"></p>
</div>
</div>
</section>
<section id="example-predicted-vs-observed-counts" class="slide level2">
<h2>Example: Predicted vs Observed Counts</h2>
<div class="fragment">
<p>Predicted mean counts <span class="math inline">\(\hat{y}_i = \lambda_{\hat{\beta}}(\text{pH}_i, \text{Biomass}_i)\)</span> as a function of observed counts <span class="math inline">\(y_i\)</span>.</p>
<div style="text-align: center;">
<p><img data-src="../images/species_prediction.png" style="width:40.0%"></p>
</div>
</div>
</section>
<section id="model-predictions-by-ph" class="slide level2">
<h2>Model Predictions by pH</h2>
<div class="fragment">
<p><strong>Lines</strong>: predicted mean counts by pH as a function of biomass</p>
<p><strong>Points</strong>: observed counts by pH as a function of biomass</p>
<div style="text-align: center;">
<p><img data-src="../images/prediction_by_ph.png" style="width:40.0%"></p>
</div>
<p><strong>Black</strong>: pH=basic; <strong>Green</strong>: pH=neutral; <strong>Red</strong>: pH=acidic</p>
</div>
</section>
<section id="predicted-distribution" class="slide level2">
<h2>Predicted Distribution</h2>
<div class="fragment">
<p>Histogram: empirical distribution<br>
Points: predicted distribution</p>
<div style="text-align: center;">
<p><img data-src="../images/distribution_species.png" style="width:50.0%"></p>
</div>
</div>
</section></section>
<section>
<section id="overdispersion" class="title-slide slide level1 center">
<h1>Overdispersion</h1>

</section>
<section id="model-limitations" class="slide level2">
<h2>Model Limitations</h2>
<div class="fragment">
<p>When we model <span class="math inline">\(Y|(X = x) \sim \mathcal P(\lambda(x))\)</span>, we have</p>
<div class="square-def">
<p><span class="math display">\[\E(Y|X = x) = \lambda(x)\]</span></p>
</div>
</div>
<div class="fragment">
<p>but also</p>
<div class="square-def">
<p><span class="math display">\[\Var(Y|X = x) = \lambda(x)\]</span></p>
</div>
</div>
<div class="fragment">
<p>This constraint is a limitation of the Poisson model.</p>
</div>
</section>
<section id="overdispersion-1" class="slide level2">
<h2>Overdispersion</h2>
<div class="fragment">
<p>Some data are <span style="background-color: lightblue;">overdispersed</span>, in the sense that</p>
<div class="square-def">
<p><span class="math display">\[\Var(Y|X = x) &gt; \E(Y|X = x)\]</span></p>
</div>
</div>
<div class="fragment">
<p>More rarely, we can find underdispersed data.</p>
</div>
<div class="fragment">
<p>In case of overdispersion, the estimated variance of estimators is underestimated.</p>
</div>
</section>
<section id="how-to-detect-overdispersion" class="slide level2">
<h2>How to Detect Overdispersion?</h2>
<div class="fragment">
<p>By assuming that <span class="math inline">\(\Var(Y|X = x) = \phi \E(Y|X = x)\)</span> where <span class="math inline">\(\phi &gt; 0\)</span>, we can estimate <span class="math inline">\(\phi\)</span> by</p>
<div class="square-def">
<p><span class="math display">\[\hat{\phi} = \frac{1}{n-p} \sum_{i=1}^n \frac{(y_i - \hat{y}_i)^2}{\hat{y}_i}\]</span></p>
</div>
<p>and test if <span class="math inline">\(\phi = 1\)</span> or not (if <span class="math inline">\(\phi = 1\)</span>, <span class="math inline">\(\hat{\phi} \sim N(1, 1/n)\)</span> when <span class="math inline">\(n \to \infty\)</span>).</p>
</div>
<div class="fragment">
<p>We can fit a <span style="background-color: yellow;">negative binomial model</span> (cf the following), and test if it is better than the Poisson model.</p>
</div>
</section>
<section id="the-quasi-poisson-model" class="slide level2">
<h2>The Quasi-Poisson Model</h2>
<ol type="1">
<li class="fragment"><p>Estimate <span style="background-color: lightblue;"><span class="math inline">\(E(Y|X = x) = \lambda_\beta(x)\)</span></span> with <span style="background-color: lightblue;"><span class="math inline">\(\lambda_\beta(x) = \exp(x^T \beta)\)</span></span> in the same way as with a Poisson model (same likelihood).</p></li>
<li class="fragment"><p>Estimate <span class="math inline">\(\phi\)</span> as in the previous slide.</p></li>
<li class="fragment"><p>Estimate the variance of <span class="math inline">\(\hat{\beta}\)</span> taking into account <span class="math inline">\(\hat{\phi}\)</span>.</p></li>
</ol>
</section>
<section id="quasi-poisson-vs-poisson-model" class="slide level2">
<h2>Quasi-Poisson VS Poisson Model</h2>
<ul>
<li class="fragment">The estimated coefficients <span class="math inline">\(\hat{\beta}\)</span> are <span style="background-color: lightgreen;">identical</span>.</li>
<li class="fragment">The predictions <span class="math inline">\(\hat{y}_i = \exp(\lambda_{\hat{\beta}}(x_i))\)</span> are <span style="background-color: lightgreen;">identical</span>.</li>
<li class="fragment">Only the <span style="background-color: orange;">estimation of standard errors differ</span>, and therefore possibly the significance of coefficients.</li>
</ul>
<div class="fragment">
<p>The estimation procedure does not rely on the “true” likelihood (because of <span class="math inline">\(\phi\)</span>): <span style="background-color: orange;">we therefore do not have access to <span class="math inline">\(L_{\text{mod}}\)</span></span>.</p>
</div>
</section>
<section id="example-plant-species-with-quasi-poisson" class="slide level2">
<h2>Example: Plant Species with Quasi Poisson</h2>
<div class="fragment">
<div class="sourceCode" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a><span class="fu">glm</span>(Species∼ pH<span class="sc">+</span> Biomass<span class="sc">+</span> pH<span class="sc">:</span>Biomass, <span class="at">family=</span>quasipoisson)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="fragment">
<div style="font-size: 60%;">
<table class="caption-top">
<colgroup>
<col style="width: 19%">
<col style="width: 14%">
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Estimate</th>
<th>Std. Error</th>
<th>t value</th>
<th>Pr(&gt;</th>
<th>t</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td>3.76812</td>
<td>0.06144</td>
<td>61.332</td>
<td>&lt; 2e-16</td>
<td>***</td>
</tr>
<tr class="even">
<td>pHlow</td>
<td>-0.81557</td>
<td>0.10268</td>
<td>-7.943</td>
<td>7.90e-12</td>
<td>***</td>
</tr>
<tr class="odd">
<td>pHmid</td>
<td>-0.33146</td>
<td>0.09203</td>
<td>-3.602</td>
<td>0.000534</td>
<td>***</td>
</tr>
<tr class="even">
<td>Biomass</td>
<td>-0.10713</td>
<td>0.01247</td>
<td>-8.590</td>
<td>3.97e-13</td>
<td>***</td>
</tr>
<tr class="odd">
<td>pHlow:Biomass</td>
<td>-0.15503</td>
<td>0.03997</td>
<td>-3.878</td>
<td>0.000208</td>
<td>***</td>
</tr>
<tr class="even">
<td>pHmid:Biomass</td>
<td>-0.03189</td>
<td>0.02304</td>
<td>-1.384</td>
<td>0.169985</td>
<td></td>
</tr>
</tbody>
</table>
<p>Signif. codes: 0 ‘<em><strong>’ 0.001 ’</strong>’ 0.01 ’</em>’ 0.05 ‘.’ 0.1 ’ ’ 1</p>
<p>(Dispersion parameter for quasipoisson family taken to be 0.9970074)</p>
<p>Null deviance: 452.346 on 89 degrees of freedom<br>
Residual deviance: 83.201 on 84 degrees of freedom<br>
AIC: NA</p>
</div>
</div>
</section>
<section id="interpretation" class="slide level2">
<h2>Interpretation</h2>
<div class="fragment">
<p><span class="math inline">\(\hat{\phi} = 0.997 \approx 1\)</span> therefore there was no overdispersion issue</p>
</div>
<div class="fragment">
<p><span style="background-color: orange;">The Residual deviance is incorrect</span>: it’s that of the Poisson model.</p>
</div>
</section>
<section id="negative-binomial-distribution" class="slide level2">
<h2>Negative Binomial Distribution</h2>
<div class="fragment">
<p>Alternative to Poisson: Negative Binomial (NB), which depends on 2 parameters:</p>
<ul>
<li class="fragment">its expectation <span class="math inline">\(\lambda &gt; 0\)</span></li>
<li class="fragment">the “number of successes” (or size) <span class="math inline">\(\theta &gt; 0\)</span></li>
</ul>
</div>
<div class="fragment">
<p>If <span class="math inline">\(Y \sim NB(\lambda, \theta)\)</span>, then for all <span class="math inline">\(k \in \mathbb{N}\)</span>,</p>
<div class="square-def">
<p><span class="math display">\[P(Y = k) = \frac{\Gamma(k + \theta)}{\Gamma(k + 1)\Gamma(\theta)} \left(\frac{\lambda}{\lambda + \theta}\right)^k \left(\frac{\theta}{\lambda + \theta}\right)^\theta\]</span></p>
</div>
</div>
</section>
<section id="properties-of-negative-binomial" class="slide level2">
<h2>Properties of Negative Binomial</h2>
<ul>
<li class="fragment"><p><span style="background-color: lightblue;">The expectation</span> of <span class="math inline">\(NB(\lambda, \theta)\)</span> equals <span style="background-color: lightblue;"><span class="math inline">\(\lambda\)</span></span>.</p></li>
<li class="fragment"><p><span style="background-color: lightgreen;">The variance</span> of <span class="math inline">\(NB(\lambda, \theta)\)</span> equals <span style="background-color: lightgreen;"><span class="math inline">\(\lambda + \lambda^2/\theta\)</span></span>.</p></li>
</ul>
<div class="fragment">
<p>This distribution can therefore model <span style="background-color: yellow;">overdispersion</span> (but not underdispersion).</p>
</div>
<div class="fragment">
<p>If <span style="background-color: lightblue;"><span class="math inline">\(\theta \to +\infty\)</span>, <span class="math inline">\(NB(\lambda, \theta) \approx P(\lambda)\)</span></span>.</p>
</div>
<div class="fragment">
<p>The Poisson distribution is therefore a special case of the NB distribution.</p>
</div>
</section>
<section id="illustration-of-nb" class="slide level2">
<h2>Illustration of NB</h2>

<img data-src="../images/negative_binomials.png" class="r-stretch"></section>
<section id="negative-binomial-glm-model" class="slide level2">
<h2>Negative Binomial GLM Model</h2>
<div class="fragment">
<p>The negative binomial GLM model assumes that</p>
<div class="square-def">
<p><span class="math display">\[Y|(X = x) \sim NB(\lambda(x), \theta)\]</span></p>
</div>
<p>where as usual <span style="background-color: lightblue;"><span class="math inline">\(\lambda(x) = \exp(x^T \beta)\)</span></span>.</p>
</div>
</section>
<section id="inference-an-other-tools-in-nb-glm-model" class="slide level2">
<h2>Inference an other Tools in NB GLM model</h2>
<div class="fragment">
<p>The estimation of <span class="math inline">\(\beta\)</span> and <span class="math inline">\(\theta\)</span> is done by <span style="background-color: yellow;">maximum likelihood</span></p>
</div>
<div class="fragment">
<p>All usual inference tools are available:</p>
<ul>
<li class="fragment"><span style="background-color: lightblue;">Wald tests</span>; <span style="background-color: lightgreen;">Deviance</span>; <span style="background-color: yellow;">AIC, BIC</span>.</li>
</ul>
</div>
<div class="fragment">
<p>If <span class="math inline">\(\hat{\theta}\)</span> is large, this is equivalent to the Poisson model.</p>
</div>
<div class="fragment">
<p>We can test the interest of the NB model <span style="background-color: yellow;">compared to the Poisson model</span> by inspecting <span class="math inline">\(\hat{\theta}\)</span>, or by <span style="background-color: yellow;">comparing their AIC and BIC criteria.</span></p>
</div>
</section>
<section id="example-plant-species-and-nb-model" class="slide level2">
<h2>Example: Plant Species and NB Model</h2>
<div class="fragment">
<div class="sourceCode" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a></a><span class="fu">glm.nb</span>(Species∼ pH<span class="sc">+</span> Biomass<span class="sc">+</span> pH<span class="sc">:</span>Biomass)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="fragment">
<div style="font-size: 50%;">
<table class="caption-top">
<colgroup>
<col style="width: 19%">
<col style="width: 14%">
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Estimate</th>
<th>Std. Error</th>
<th>z value</th>
<th>Pr(&gt;</th>
<th>z</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td>3.76813</td>
<td>0.06154</td>
<td>61.235</td>
<td>&lt; 2e-16</td>
<td>***</td>
</tr>
<tr class="even">
<td>pHlow</td>
<td>-0.81557</td>
<td>0.10284</td>
<td>-7.930</td>
<td>2.19e-15</td>
<td>***</td>
</tr>
<tr class="odd">
<td>pHmid</td>
<td>-0.33146</td>
<td>0.09217</td>
<td>-3.596</td>
<td>0.000323</td>
<td>***</td>
</tr>
<tr class="even">
<td>Biomass</td>
<td>-0.10713</td>
<td>0.01249</td>
<td>-8.577</td>
<td>&lt; 2e-16</td>
<td>***</td>
</tr>
<tr class="odd">
<td>pHlow:Biomass</td>
<td>-0.15503</td>
<td>0.04003</td>
<td>-3.873</td>
<td>0.000108</td>
<td>***</td>
</tr>
<tr class="even">
<td>pHmid:Biomass</td>
<td>-0.03189</td>
<td>0.02308</td>
<td>-1.382</td>
<td>0.166978</td>
<td></td>
</tr>
</tbody>
</table>
<p>Signif. codes: 0 ‘<em><strong>’ 0.001 ’</strong>’ 0.01 ’</em>’ 0.05 ‘.’ 0.1 ’ ’ 1</p>
<p>(Dispersion parameter for Negative Binomial(212058.3) family taken to be 1)</p>
<p>Null deviance: 452.307 on 89 degrees of freedom<br>
Residual deviance: 83.194 on 84 degrees of freedom<br>
AIC: 516.39</p>
</div>
</div>
<div class="fragment">
<p><span class="math inline">\(\hat{\theta} = 212058.3\)</span> therefore the model is equivalent to the Poisson model.</p>
</div>
<div class="fragment">
<p>This is confirmed via the AIC.</p>
</div>
</section></section>
<section>
<section id="zero-inflated-models" class="title-slide slide level1 center">
<h1>Zero-inflated Models</h1>

</section>
<section id="the-problem" class="slide level2">
<h2>The Problem</h2>
<div class="fragment">
<p>When <span class="math inline">\(Y\)</span> is a count variable, it is not uncommon for <span style="background-color: yellow;"><span class="math inline">\(Y = 0\)</span> to appear very often</span> in the sample.</p>
</div>
<div class="fragment">
<p><strong>Example 1</strong>: <span class="math inline">\(Y\)</span>: amount of rain (in mm) that fell each day.</p>
</div>
<div class="fragment">
<p><strong>Example 2</strong>: <span class="math inline">\(Y\)</span>: amount of alcohol (in glasses) consumed each week.</p>
</div>
<div class="fragment">
<div style="text-align: center;">
<p><img data-src="../images/zero_inflated_dist.png" style="width:30.0%"></p>
</div>
</div>
</section>
<section id="model-inadequacy" class="slide level2">
<h2>Model Inadequacy</h2>
<div class="fragment">
<p>A <span style="background-color: orange;">Poisson or Negative Binomial</span> model is <span style="background-color: orange;">not adapted</span>.</p>
</div>
<div class="fragment">
<p>Generally two “populations” that explain this phenomenon:</p>
<ul>
<li class="fragment">one for which <span class="math inline">\(Y = 0\)</span> systematically</li>
<li class="fragment">one for which <span class="math inline">\(Y \geq 0\)</span> (or <span class="math inline">\(Y &gt; 0\)</span>)</li>
</ul>
</div>
<div class="fragment">
<p>We can consider two modelings in this spirit:</p>
<ul>
<li class="fragment">The <span style="background-color: yellow;">zero-inflated</span> model (<span class="math inline">\(Y = 0\)</span> versus <span class="math inline">\(Y \geq 0\)</span>)</li>
<li class="fragment">The Hurdle model (<span class="math inline">\(Y = 0\)</span> versus <span class="math inline">\(Y &gt; 0\)</span>)</li>
</ul>
</div>
<div class="fragment">
<p>We present below the <span style="background-color: yellow;">zero-inflated</span> model.</p>
</div>
</section>
<section id="zip-model-definition" class="slide level2">
<h2>ZIP Model Definition</h2>
<div class="fragment">
<p>The ZIP (Zero-Inflated Poisson) model assumes that</p>
<div class="square-def">
<p><span class="math display">\[Y|(X = x) = \begin{cases}
0 &amp; \text{with probability } q(x) \\
P(\lambda(x)) &amp; \text{with probability } 1 - q(x)
\end{cases}\]</span></p>
</div>
<p>where</p>
<div class="square-def">
<p><span class="math display">\[\lambda(x) = \exp(x^T \beta) \quad \text{and} \quad q(x) = \text{logit}^{-1}(x^T \gamma)\]</span></p>
</div>
</div>
</section>
<section id="two-mixed-populations" class="slide level2">
<h2>Two Mixed Populations</h2>
<div class="fragment">
<p>Thus two populations mix:</p>
<ul>
<li class="fragment">For one, <span class="math inline">\(Y\)</span> is always <span class="math inline">\(0\)</span>. For the other, <span class="math inline">\(Y \in \mathbb{N}\)</span>.</li>
<li class="fragment">A logistic model explains membership to one or the other population.</li>
<li class="fragment">A Poisson log-linear model is used for the second.</li>
</ul>
</div>
</section>
<section id="probability-distribution" class="slide level2">
<h2>Probability Distribution</h2>
<div class="fragment">
<p>With this model, we therefore have</p>
<div class="square-def">
<p><span class="math inline">\(P(Y = 0|X = x) = q_\gamma(x) + (1 - q_\gamma(x))e^{-\lambda_\beta(x)}\)</span></p>
</div>
</div>
<div class="fragment">
<div class="square-def">
<p><span class="math inline">\(P(Y = k|X = x) = (1 - q_\gamma(x))e^{-\lambda_\beta(x)} \frac{\lambda_\beta(x)^k}{k!}\)</span></p>
</div>
<p>where <span style="background-color: lightblue;"><span class="math inline">\(\lambda_\beta(x) = \exp(x^T \beta)\)</span> and <span class="math inline">\(q_\gamma(x) = \text{logit}^{-1}(x^T \gamma)\)</span></span>.</p>
</div>
<div class="fragment">
<p>We deduce</p>
<div class="square-def">
<p><span class="math inline">\(E(Y|X = x) = (1 - q_\gamma(x))\lambda_\beta(x)\)</span></p>
</div>
</div>
</section>
<section id="inference" class="slide level2">
<h2>Inference</h2>
<div class="fragment">
<p>For inference:</p>
<ul>
<li class="fragment">We can write the log-likelihood as a function of <span class="math inline">\(\beta\)</span> and <span class="math inline">\(\gamma\)</span></li>
<li class="fragment">We obtain estimators by maximum likelihood</li>
<li class="fragment">And we have access to usual inference tools</li>
</ul>
</div>
<div class="fragment">
<p>Under R: <code>zeroinfl</code> function from the <code>pscl</code> package.</p>
</div>
</section>
<section id="zinb-model-definition" class="slide level2">
<h2>ZINB Model Definition</h2>
<div class="fragment">
<p>Similarly, the ZINB (Zero-Inflated Negative Binomial) model is</p>
<div class="square-def">
<p><span class="math display">\[Y|(X = x) = \begin{cases}
0 &amp; \text{with probability } q(x) \\
NB(\lambda(x), \theta) &amp; \text{with probability } 1 - q(x)
\end{cases}\]</span></p>
</div>
<p>where <span class="math inline">\(\theta &gt; 0\)</span> and</p>
<p><span style="background-color: lightblue;"><span class="math inline">\(\lambda(x) = \exp(x^T \beta) \quad \text{and} \quad q(x) = \text{logit}^{-1}(x^T \gamma)\)</span></span></p>
</div>
<div class="fragment">
<p>Under R: <code>zeroinfl</code> function with the option <code>dist="negbin"</code>.</p>
</div>
</section>
<section id="example-horseshoe-crabs" class="slide level2">
<h2>Example: Horseshoe Crabs</h2>
<div class="fragment">
<p>Number of male satellites on female horseshoe crabs.</p>
</div>
<div class="fragment">
<div style="text-align: center;">
<p><img data-src="../images/zinb1.png" style="width:40.0%"></p>
</div>
</div>
<div class="fragment">
<div style="font-size: 80%;">
<p>We want to model the number of satellites (<code>satell</code>) as a function of the weight of the horseshoe crab (<code>weight</code>) and its color (<code>color</code>, from 1 to 4, ≈ age).</p>
</div>
</div>
</section>
<section id="example-poisson-log-linear-model" class="slide level2">
<h2>Example: Poisson log-linear Model :</h2>
<div class="fragment">
<div class="sourceCode" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a><span class="fu">glm</span>(satell∼weight<span class="sc">+</span>color,<span class="at">family=</span>’poisson’,<span class="at">data=</span>crabs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="fragment">
<div style="font-size: 50%;">
<table class="caption-top">
<colgroup>
<col style="width: 19%">
<col style="width: 14%">
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Estimate</th>
<th>Std. Error</th>
<th>z value</th>
<th>Pr(&gt;</th>
<th>z</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td>0.08855</td>
<td>0.25443</td>
<td>0.348</td>
<td>0.72783</td>
<td></td>
</tr>
<tr class="even">
<td>weight</td>
<td>0.54588</td>
<td>0.06749</td>
<td>8.088</td>
<td>6.05e-16</td>
<td>***</td>
</tr>
<tr class="odd">
<td>color</td>
<td>-0.17282</td>
<td>0.06155</td>
<td>-2.808</td>
<td>0.00499</td>
<td>**</td>
</tr>
</tbody>
</table>
<p>Signif. codes: 0 ‘<em><strong>’ 0.001 ’</strong>’ 0.01 ’</em>’ 0.05 ‘.’ 0.1 ’ ’ 1</p>
<p>(Dispersion parameter for poisson family taken to be 1)</p>
<p>Null deviance: 632.79 on 172 degrees of freedom<br>
Residual deviance: 552.79 on 170 degrees of freedom<br>
AIC: 914.09</p>
</div>
<p>The model is significant but the fit is poor (the deviance is very high)</p>
</div>
</section>
<section id="example-log-linear-poisson" class="slide level2">
<h2>Example: Log-Linear Poisson</h2>
<div style="text-align: center;">
<p><img data-src="../images/zinb2.png" style="width:40.0%"></p>
</div>
<ul>
<li class="fragment">In red: empirical distribution of satell on the sample</li>
<li class="fragment">Points: predicted distribution</li>
</ul>
</section>
<section id="example-nb-model" class="slide level2">
<h2>Example: NB Model</h2>
<div class="fragment">
<div class="sourceCode" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a></a><span class="fu">glm.nb</span>(satell∼weight<span class="sc">+</span>color,<span class="at">data=</span>crabs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="fragment">
<div style="font-size: 60%;">
<table class="caption-top">
<colgroup>
<col style="width: 19%">
<col style="width: 14%">
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Estimate</th>
<th>Std. Error</th>
<th>z value</th>
<th>Pr(&gt;</th>
<th>z</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td>-0.3220</td>
<td>0.5540</td>
<td>-0.581</td>
<td>0.561</td>
<td></td>
</tr>
<tr class="even">
<td>weight</td>
<td>0.7072</td>
<td>0.1612</td>
<td>4.387</td>
<td>1.15e-05</td>
<td>***</td>
</tr>
<tr class="odd">
<td>color</td>
<td>-0.1734</td>
<td>0.1199</td>
<td>-1.445</td>
<td>0.148</td>
<td></td>
</tr>
</tbody>
</table>
<p>Signif. codes: 0 ‘<em><strong>’ 0.001 ’</strong>’ 0.01 ’</em>’ 0.05 ‘.’ 0.1 ’ ’ 1</p>
<p>(Dispersion parameter for Negative Binomial(0.9555) family taken to be 1)</p>
<p>Null deviance: 219.50 on 172 degrees of freedom<br>
Residual deviance: 196.64 on 170 degrees of freedom<br>
AIC: 754.45</p>
</div>
</div>
<div class="fragment">
<p>It’s better… (by the way: color doesn’t seem significant)</p>
</div>
</section>
<section id="example-nb-model-1" class="slide level2">
<h2>Example: NB Model</h2>
<div style="text-align: center;">
<p><img data-src="../images/zinb3.png" style="width:40.0%"></p>
</div>
<div class="fragment">
<p>Still not very satisfactory.</p>
</div>
</section>
<section id="example-zip-model" class="slide level2">
<h2>Example: ZIP Model</h2>
<div class="fragment">
<div class="sourceCode" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a><span class="fu">zeroinfl</span>(satell∼weight <span class="sc">|</span> weight<span class="sc">+</span>color,<span class="at">dist=</span><span class="st">"poisson"</span>,<span class="at">data=</span>crabs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="fragment">
<div style="font-size: 50%;">
<p><strong>Count model coefficients (poisson with log link):</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 19%">
<col style="width: 14%">
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Estimate</th>
<th>Std. Error</th>
<th>z value</th>
<th>Pr(&gt;</th>
<th>z</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td>1.00152</td>
<td>0.20793</td>
<td>4.817</td>
<td>1.46e-06</td>
<td>***</td>
</tr>
<tr class="even">
<td>weight</td>
<td>0.19020</td>
<td>0.07572</td>
<td>2.512</td>
<td>0.012</td>
<td>*</td>
</tr>
</tbody>
</table>
<p><strong>Zero-inflation model coefficients (binomial with logit link):</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 19%">
<col style="width: 14%">
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Estimate</th>
<th>Std. Error</th>
<th>z value</th>
<th>Pr(&gt;</th>
<th>z</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td>1.9621</td>
<td>1.1448</td>
<td>1.714</td>
<td>0.0866</td>
<td>.</td>
</tr>
<tr class="even">
<td>weight</td>
<td>-1.6630</td>
<td>0.3943</td>
<td>-4.218</td>
<td>2.47e-05</td>
<td>***</td>
</tr>
<tr class="odd">
<td>color</td>
<td>0.5329</td>
<td>0.2305</td>
<td>2.312</td>
<td>0.0208</td>
<td>*</td>
</tr>
</tbody>
</table>
<p>Signif. codes: 0 ‘<em><strong>’ 0.001 ’</strong>’ 0.01 ’</em>’ 0.05 ‘.’ 0.1 ’ ’ 1</p>
<p>Number of iterations in BFGS optimization: 9<br>
Log-likelihood: -360.8 on 5 Df</p>
</div>
</div>
</section>
<section id="example-zip-model-1" class="slide level2">
<h2>Example: ZIP Model</h2>
<div class="fragment">
<p>We see the estimation result <span style="background-color: yellow;">explaining the mixture</span> of the two “populations” forming the model.</p>
</div>
<div class="fragment">
<p>First population: <span style="background-color: yellow;">Poisson log-linear model</span> with expectation <span class="math inline">\(\lambda\)</span> where <span style="background-color: lightblue;"><span class="math inline">\(\lambda(\text{weight}) = \exp(1 + 0.19 \times \text{weight})\)</span></span></p>
</div>
<div class="fragment">
<p>Second population is <span class="math inline">\(0\)</span>. The probability <span class="math inline">\(q\)</span> of belonging to the second one is</p>
<p><span style="background-color: lightblue;"><span class="math inline">\(q(\text{wgt}, \text{col}) = \text{logit}^{-1}(1.96 - 1.66 \times \text{wgt} + 0.53 \times \text{col})\)</span></span></p>
</div>
</section>
<section id="example-zip-model-2" class="slide level2">
<h2>Example: ZIP Model</h2>
<div style="text-align: center;">
<p><img data-src="../images/zinb4.png" style="width:40.0%"></p>
</div>
<div class="fragment">
<p>Much more convincing.</p>
</div>
</section>
<section id="example-zinb-model" class="slide level2">
<h2>Example: ZINB Model</h2>
<div class="fragment">
<div class="sourceCode" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a></a><span class="fu">zeroinfl</span>(satell∼weight <span class="sc">|</span> weight<span class="sc">+</span>color,<span class="at">dist=</span><span class="st">"negbin"</span>,<span class="at">data=</span>crabs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="fragment">
<div style="font-size: 60%;">
<p><strong>Count model coefficients (negbin with log link):</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 19%">
<col style="width: 14%">
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Estimate</th>
<th>Std. Error</th>
<th>z value</th>
<th>Pr(&gt;</th>
<th>z</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td>0.8961</td>
<td>0.3070</td>
<td>2.919</td>
<td>0.00351</td>
<td>**</td>
</tr>
<tr class="even">
<td>weight</td>
<td>0.2169</td>
<td>0.1125</td>
<td>1.928</td>
<td>0.05383</td>
<td>.</td>
</tr>
<tr class="odd">
<td>Log(theta)</td>
<td>1.5802</td>
<td>0.3574</td>
<td>4.422</td>
<td>9.79e-06</td>
<td>***</td>
</tr>
</tbody>
</table>
<p><strong>Zero-inflation model coefficients (binomial with logit link):</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 19%">
<col style="width: 14%">
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Estimate</th>
<th>Std. Error</th>
<th>z value</th>
<th>Pr(&gt;</th>
<th>z</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td>1.8663</td>
<td>1.2415</td>
<td>1.503</td>
<td>0.133</td>
<td></td>
</tr>
<tr class="even">
<td>weight</td>
<td>-1.7531</td>
<td>0.4429</td>
<td>-3.958</td>
<td>7.55e-05</td>
<td>***</td>
</tr>
<tr class="odd">
<td>color</td>
<td>0.5985</td>
<td>0.2572</td>
<td>2.326</td>
<td>0.020</td>
<td>*</td>
</tr>
</tbody>
</table>
<p>Signif. codes: 0 ‘<em><strong>’ 0.001 ’</strong>’ 0.01 ’</em>’ 0.05 ‘.’ 0.1 ’ ’ 1</p>
<p>Theta = 4.8558<br>
Number of iterations in BFGS optimization: 11<br>
Log-likelihood: -349.9 on 6 Df</p>
</div>
</div>
</section>
<section id="example-zinb-model-1" class="slide level2">
<h2>Example: ZINB Model</h2>
<div style="text-align: center;">
<p><img data-src="../images/zinb5.png" style="width:40.0%"></p>
</div>
</section>
<section id="zinb-model-interpretation" class="slide level2">
<h2>ZINB Model Interpretation</h2>
<div class="fragment">
<p>The output is read in the same way as for the ZIP model</p>
</div>
<div class="fragment">
<p>There is the parameter <span class="math inline">\(\theta\)</span> in addition, from the NB distribution</p>
</div>
<div class="fragment">
<p><span class="math inline">\(\theta\)</span> is not “infinite”: the model therefore does not reduce to the ZIP model.</p>
<ul>
<li class="fragment"><p>A deviance test shows that ZINB is preferable to ZIP</p></li>
<li class="fragment"><p>This is also confirmed by the AIC and BIC criteria.</p></li>
</ul>
</div>
</section>
<section id="example-conclusion" class="slide level2">
<h2>Example: Conclusion</h2>
<div class="fragment">
<p>A portion of horseshoe crabs (the smallest and oldest) have no male satellites.</p>
</div>
<div class="fragment">
<p>The probability of belonging to this population is estimated at</p>
<p><span style="background-color: lightblue;"><span class="math inline">\(q(\text{wht}, \text{col}) = \text{logit}^{-1}(1.87 - 1.75 \times \text{wht} + 0.60 \times \text{col})\)</span></span></p>
</div>
<div class="fragment">
<p>For the other portion of horseshoe crabs, they have on average more satellites the larger they are. This average is estimated at</p>
<p><span style="background-color: lightblue;"><span class="math inline">\(\lambda(\text{wht}) = \exp(0.90 + 0.22 \times \text{wht})\)</span></span></p>
</div>
<div class="fragment">
<p>Distribution cna be modeled as <span style="background-color: lightblue;"><span class="math inline">\(NB(\lambda(\text{wht}), \theta)\)</span> where <span class="math inline">\(\theta = 4.86\)</span></span>.</p>


</div>
</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: false,

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>